In [1]:
%pip install --upgrade --quiet google-cloud-aiplatform google-cloud-aiplatform[evaluation]

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 41.2/41.2 kB 3.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.9/7.9 MB 64.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.0/9.0 MB 88.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 119.7/119.7 kB 12.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 739.1/739.1 kB 44.3 MB/s eta 0:00:00

In [1]:
import datetime
import nest_asyncio
import pandas as pd
from IPython.display import display, Markdown, HTML

import vertexai
from vertexai.generative_models import GenerativeModel

pd.set_option('display.max_colwidth', None)

In [2]:
PROJECT_ID = "qwiklabs-gcp-02-f6ae179d9554"
LOCATION = "us-west1"
import vertexai
vertexai.init(project=PROJECT_ID, location=LOCATION)

In [3]:
!gcloud storage cp gs://partner-genai-bucket/genai065/apartment_table.csv .

Copying gs://partner-genai-bucket/genai065/apartment_table.csv to file://./apartment_table.csv

In [4]:
apartment_df = pd.read_csv("apartment_table.csv")
apartment_df.head()

,Address,Unit,Sqft,Bedrooms,Elevator,Washer & Dryer in Unit,Pets Allowed,Notable features
0,"123 West 14th Street, New York, NY 10014",2E,550,2,yes,no,yes,"doorman, pool in the building, shared roof deck with grills"
1,"456 East 57th Street, New York, NY 10022",1A,789,1,no,yes,no,"bike room, package service"
2,"789 Broadway, New York, NY 10003",C,999,3,yes,yes,yes,"excellent laundry room, great city views"
3,"1011 5th Avenue, New York, NY 10028",30,1024,2,no,no,yes,"great view of Central Park, high ceilings"
4,"2222 Park Avenue, New York, NY 10017",4F,1234,1,no,yes,no,right next to soccer fields at the park

In [5]:
apartment_records = apartment_df.to_dict(orient='records')
apartment_records[0]

{'Address': '123 West 14th Street, New York, NY 10014',
 'Unit': '2E',
 'Sqft': 550,
 'Bedrooms': 2,
 'Elevator': 'yes',
 'Washer & Dryer in Unit': 'no',
 'Pets Allowed': 'yes',
 'Notable features': 'doorman, pool in the building, shared roof deck with grills'}

In [7]:
model = GenerativeModel(
  "gemini-2.5-pro",
  generation_config={
      "temperature": 0,
      "top_p": 0.4,
  },
)

prompt = "Write a one paragraph apartment listing to promote this apartment. Make it sound amazing: "

# View the response using Markdown to format it nicely for notebook viewing
Markdown(model.generate_content(prompt + str(apartment_records[0])).text)

Experience the pinnacle of New York City living at 123 West 14th Street, where the vibrant energy of Chelsea and the West Village is at your doorstep. This sun-drenched, two-bedroom home offers a flexible and efficient layout, perfect for creating your ideal urban sanctuary. The true luxury, however, lies in the building's unparalleled amenities. Imagine starting your day with a swim in the indoor pool, being welcomed home by your doorman, and spending summer evenings grilling with friends on the spectacular shared roof deck while soaking in breathtaking skyline views. This pet-friendly, elevator building provides a resort-style living experience that combines ultimate convenience with pure indulgence, offering a rare and incredible opportunity to have it all in the heart of Manhattan.

In [8]:
# Context is the supplemental information you provide the
# model, usually specific to a given query or example,
# that it needs to fulfill your instructions.
# In this case, the context is each apartment record.
contexts = [str(record) for record in apartment_records]
# The full prompt combines the prompt instructions you
# created earlier with the context for each apartment.
full_prompts = [prompt + str(record) for record in apartment_records]

print(full_prompts[0])

Write a one paragraph apartment listing to promote this apartment. Make it sound amazing: {'Address': '123 West 14th Street, New York, NY 10014', 'Unit': '2E', 'Sqft': 550, 'Bedrooms': 2, 'Elevator': 'yes', 'Washer & Dryer in Unit': 'no', 'Pets Allowed': 'yes', 'Notable features': 'doorman, pool in the building, shared roof deck with grills'}

In [9]:
eval_dataset = pd.DataFrame({
    "prompt": full_prompts[0:5],
})

In [10]:
from vertexai.evaluation import (
    MetricPromptTemplateExamples,
    EvalTask,
    PairwiseMetric,
    PairwiseMetricPromptTemplate,
    PointwiseMetric,
    PointwiseMetricPromptTemplate,
)

MetricPromptTemplateExamples.list_example_metric_names()

['coherence',
 'fluency',
 'safety',
 'groundedness',
 'instruction_following',
 'verbosity',
 'text_quality',
 'summarization_quality',
 'question_answering_quality',
 'multi_turn_chat_quality',
 'multi_turn_safety',
 'pairwise_coherence',
 'pairwise_fluency',
 'pairwise_safety',
 'pairwise_groundedness',
 'pairwise_instruction_following',
 'pairwise_verbosity',
 'pairwise_text_quality',
 'pairwise_summarization_quality',
 'pairwise_question_answering_quality',
 'pairwise_multi_turn_chat_quality',
 'pairwise_multi_turn_safety']

In [11]:
print(MetricPromptTemplateExamples.get_prompt_template('groundedness'))

# Instruction
You are an expert evaluator. Your task is to evaluate the quality of the responses generated by AI models.
We will provide you with the user input and an AI-generated response.
You should first read the user input carefully for analyzing the task, and then evaluate the quality of the responses based on the criteria provided in the Evaluation section below.
You will assign the response a rating following the Rating Rubric and Evaluation Steps. Give step by step explanations for your rating, and only choose ratings from the Rating Rubric.


# Evaluation
## Metric Definition
You will be assessing groundedness, which measures the ability to provide or reference information included only in the user prompt.

## Criteria
Groundedness: The response contains information included only in the user prompt. The response does not reference any outside information.

## Rating Rubric
1: (Fully grounded). All aspects of the response are attributable to the context.
0: (Not fully grounded). The entire response or a portion of the response is not attributable to the context provided by the user prompt.

## Evaluation Steps
STEP 1: Assess the response in aspects of Groundedness. Identify any information in the response not present in the prompt and provide assessment according to the criterion.
STEP 2: Score based on the rating rubric. Give a brief rationale to explain your evaluation considering Groundedness.


# User Inputs and AI-generated Response
## User Inputs
### Prompt
{prompt}

## AI-generated Response
{response}

In [12]:
eval_task = EvalTask(
  dataset=eval_dataset,
  metrics=[MetricPromptTemplateExamples.Pointwise.GROUNDEDNESS],
  experiment="apartment-listing-generation",
)

In [13]:
run_ts = datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
eval_result = eval_task.evaluate(
  model=model,
  experiment_run_name=f"apt-gen-{run_ts}"
  )

# You might want to keep track of your results in a list
# which you will use to plot your results later on
eval_results_to_compare = []
eval_results_to_compare.append(eval_result)

INFO:vertexai.evaluation.eval_task:Logging Eval Experiment metadata: {'model_name': 'publishers/google/models/gemini-2.5-pro', 'temperature': 0, 'top_p': 0.4}
INFO:vertexai.evaluation._evaluation:Generating a total of 5 responses from Gemini model gemini-2.5-pro.
100%|██████████| 5/5 [00:18<00:00,  3.66s/it]
INFO:vertexai.evaluation._evaluation:All 5 responses are successfully generated from Gemini model gemini-2.5-pro.
INFO:vertexai.evaluation._evaluation:Multithreaded Batch Inference took: 18.32540568500002 seconds.
INFO:vertexai.evaluation._evaluation:Computing metrics with a total of 5 Vertex Gen AI Evaluation Service API requests.
100%|██████████| 5/5 [00:10<00:00,  2.15s/it]
INFO:vertexai.evaluation._evaluation:All 5 metric requests are successfully computed.
INFO:vertexai.evaluation._evaluation:Evaluation Took:10.746042163000027 seconds

In [14]:
eval_result.summary_metrics

{'row_count': 5, 'groundedness/mean': np.float64(1.0), 'groundedness/std': 0.0}

In [15]:
eval_result.metrics_table

,prompt,response,groundedness/explanation,groundedness/score
0,"Write a one paragraph apartment listing to promote this apartment. Make it sound amazing: {'Address': '123 West 14th Street, New York, NY 10014', 'Unit': '2E', 'Sqft': 550, 'Bedrooms': 2, 'Elevator': 'yes', 'Washer & Dryer in Unit': 'no', 'Pets Allowed': 'yes', 'Notable features': 'doorman, pool in the building, shared roof deck with grills'}","Experience the pinnacle of New York City living in this exceptional two-bedroom home, perfectly situated at the vibrant crossroads of the West Village and Chelsea. Your pet-friendly, elevator building offers a lifestyle of unparalleled luxury and convenience, complete with a full-time doorman to welcome you home. Spend your summers taking a refreshing dip in the exclusive residents' pool or hosting unforgettable barbecues with friends on the stunning shared roof deck, equipped with grills and breathtaking city views. This thoughtfully designed apartment is more than just a place to live—it's your private sanctuary and your all-access pass to the resort-style amenities you deserve, all in the heart of the world's most exciting city.","The response is fully grounded because all information comes from the provided listing details, creatively presented as a marketing pitch.",1.0
1,"Write a one paragraph apartment listing to promote this apartment. Make it sound amazing: {'Address': '456 East 57th Street, New York, NY 10022', 'Unit': '1A', 'Sqft': 789, 'Bedrooms': 1, 'Elevator': 'no', 'Washer & Dryer in Unit': 'yes', 'Pets Allowed': 'no', 'Notable features': 'bike room, package service'}","Discover your personal oasis at a prestigious East 57th Street address, where classic New York charm meets modern convenience. This stunning, generously-proportioned one-bedroom home spans an impressive 789 square feet, offering an expansive and tranquil retreat from the city's hustle. Experience true urban luxury with the ultimate convenience of your own in-unit washer and dryer, a game-changer for city living. Located on the accessible first floor, you can bypass the wait for elevators entirely, making coming and going an absolute breeze. Further enhancing your seamless lifestyle are the building's thoughtful amenities, including a secure package service and a dedicated bike room, ensuring this is more than just an apartment—it's your perfectly appointed sanctuary in the heart of it all.","The response only contains information provided in the prompt, such as address, square footage, and amenities.",1.0
2,"Write a one paragraph apartment listing to promote this apartment. Make it sound amazing: {'Address': '789 Broadway, New York, NY 10003', 'Unit': 'C', 'Sqft': 999, 'Bedrooms': 3, 'Elevator': 'yes', 'Washer & Dryer in Unit': 'yes', 'Pets Allowed': 'yes', 'Notable features': 'excellent laundry room, great city views'}","Experience the ultimate New York lifestyle from this stunning 3-bedroom home, perched high above the iconic energy of Broadway. Spanning nearly 1000 square feet, this sun-drenched sanctuary offers three generously sized bedrooms and the ultimate city convenience of your own in-unit washer and dryer, making laundry day a breeze. Your daily life is made effortless in this pet-friendly elevator building, where breathtaking city views provide a dazzling backdrop to every moment. This is more than an apartment; it's your private oasis in the heart of it all, offering an unparalleled blend of space, luxury, and prime location.","All aspects of the response, including the details about the apartment's address, unit number, square footage, number of bedrooms, elevator, in-unit washer and dryer, pet-friendly policy, and notable features, are directly attributable to the context provided in the user prompt.",1.0
3,"Write a one paragraph apartment listing to promote this apartment. Make it sound amazing: {'Address': '1011 5th Avenue, New York, NY 10028', 'Unit': '30', 'Sqft': 1024, 'Bedrooms': 2, 'Elevator': 'no', 'Washer & Dryer in Unit': 'no', 'Pets Allowed': 'yes', 'Notable features': 'great view of Central Park, high ceilings'}","Wake up to breathtaking, direct views of Central Park from this spectacular two-bedroom residence on iconic Fifth Avenue. Soaring high ceilings and oversized windows flood the generous 1,024 sq. ft. layout with natural light, creating an airy and expansive atmosphere perfect for both relaxing and entertaining. This pet-friendly haven offers a rare opportunity to experience the pinnacle of New York City living, where the city's most famous park is your personal front yard and the best of Manhattan is right at your doorstep.",All information presented in the response is attributable to the user prompt; it successfully makes the apartment sound amazing using only the details provided.,1.0
4,"Write a one paragraph apartment listing to promote this apartment. Make it sound amazing: {'Address': '2222 Park Avenue, New York, NY 10017', 'Unit': '4F', 'Sqft': 1234, 'Bedrooms': 1, 'Elevator': 'no', 'Washer & Dryer in Unit': 'yes', 'Pets Allowed': 'no', 'Notable features': 'right next to soccer fields at the park'}","Escape the city bustle in this exceptionally rare and expansive one-bedroom sanctuary on prestigious Park Avenue. Boasting an unheard-of 1,234 square feet, this stunning home provides a loft-like feel with ample room to live, work, and entertain, all complemented by the ultimate convenience of an in-unit washer and dryer. Step outside your door and find your front yard is a vibrant park, complete with soccer fields for an active lifestyle right at your doorstep. This unique, sun-drenched residence offers a perfect blend of massive indoor space and outdoor recreation that is simply impossible to find elsewhere in New York City.","All aspects of the response, including the address, unit number, square footage, number of bedrooms, presence of a washer and dryer, pet policy, and proximity to soccer fields, are attributable to the context provided in the prompt.",1.0

In [16]:
# This is a minor update, but should stop the model from
# inventing as many details about each apartment.
updated_prompt = "Write a one paragraph apartment listing highlighting the best known features of this apartment. Use only the details included in the following information: "

updated_full_prompts = [updated_prompt + str(record) for record in apartment_records]

updated_eval_dataset = pd.DataFrame(
  {
      "prompt": updated_full_prompts[0:5]
  }
)

In [17]:
updated_eval_task = EvalTask(
  dataset=updated_eval_dataset,
  metrics=[MetricPromptTemplateExamples.Pointwise.GROUNDEDNESS],
  experiment="apartment-listing-generation",
)

run_ts = datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
updated_result = updated_eval_task.evaluate(
  model=model,
  experiment_run_name=f"apt-gen-{run_ts}"
)

# Append the new result to your results
eval_results_to_compare.append(updated_result)

# Preview the summary
print(updated_result.summary_metrics)

INFO:vertexai.evaluation.eval_task:Logging Eval Experiment metadata: {'model_name': 'publishers/google/models/gemini-2.5-pro', 'temperature': 0, 'top_p': 0.4}
INFO:vertexai.evaluation._evaluation:Generating a total of 5 responses from Gemini model gemini-2.5-pro.
100%|██████████| 5/5 [00:15<00:00,  3.05s/it]
INFO:vertexai.evaluation._evaluation:All 5 responses are successfully generated from Gemini model gemini-2.5-pro.
INFO:vertexai.evaluation._evaluation:Multithreaded Batch Inference took: 15.267483961999972 seconds.
INFO:vertexai.evaluation._evaluation:Computing metrics with a total of 5 Vertex Gen AI Evaluation Service API requests.
100%|██████████| 5/5 [00:01<00:00,  4.35it/s]
INFO:vertexai.evaluation._evaluation:All 5 metric requests are successfully computed.
INFO:vertexai.evaluation._evaluation:Evaluation Took:1.1569987109999715 seconds

{'row_count': 5, 'groundedness/mean': np.float64(1.0), 'groundedness/std': 0.0}

In [18]:
import plotly.graph_objects as go
def plot_bar_plot(eval_results, metrics=None):
  fig = go.Figure()
  data = []
  for eval_result in eval_results:
      summary_metrics = eval_result.summary_metrics
      if metrics:
          summary_metrics = {
              k: summary_metrics[k]
              for k, v in summary_metrics.items()
              if any(selected_metric in k for selected_metric in metrics)
          }


      data.append(
          go.Bar(
              x=list(summary_metrics.keys()),
              y=list(summary_metrics.values()),
              name=eval_result.metadata["experiment_run"]
          )
      )
  fig = go.Figure(data=data)


  # Change the bar mode
  fig.update_layout(barmode="group")
  fig.show()


plot_bar_plot(eval_results_to_compare, metrics=["groundedness/mean"])